/**
 * OpenAppSec generator (PRD R2.4).
 *
 * Reads a SpecIR and emits an OpenAppSec declarative policy YAML.
 * Primary mapping: x-security.request.schema → schemaValidation rules.
 * Secondary: rateLimit → rate-limit practices.
 * Marks auth, cors, ipPolicy, mtls, cacheable as partial/unsupported in the
 * capability matrix — OpenAppSec is a WAF-style enforcement layer, not an
 * identity provider.
 */

import yaml from 'js-yaml';
import type {
  CapabilityMatrix,
  ConfigArtifact,
  Generator,
  SpecIR,
} from '@writ/core';
import { buildDoc, buildOpenApiFragment } from './policy.js';
import { collectSsrfPolicyWarnings } from '../ssrf-policy-check.js';

export interface OpenAppSecGenerator extends Generator {
  readonly lastWarnings: readonly string[];
}

let openappsecLastWarnings: string[] = [];

const HEADER = [
  '# Generated by Writ — DO NOT EDIT BY HAND.',
  '# Target: open-appsec.io (flat local_policy.yaml format)',
  '# Source: annotated OpenAPI spec (x-security)',
  '#',
  '# Honest notes about the open-appsec mapping:',
  '#  - Per-property request schema is enforced via the sibling',
  '#    `openapi-schema.yaml` artifact, referenced by the threat-prevention',
  '#    practice as `openapi-schema-validation.files:`. Mount both files at',
  '#    the same path inside the agent container (default: /ext/appsec/).',
  '#  - Per-property `mitigates:` hints and the full property tree are also',
  '#    preserved under `writ-extended:` for Writ drift detection',
  '#    (open-appsec ignores unknown top-level keys).',
  '#  - Authentication (JWT/OAuth), authorization (rule-based), and request',
  '#    HMAC signatures are NOT enforceable by open-appsec — it is an L7',
  '#    inspection layer, not an identity layer. Place an OIDC/auth sidecar',
  '#    in front of the WAF.',
  '#  - Rate-limit support is per-URI (no per-key partitioning). Per-user or',
  '#    per-api-key rate limits silently degrade to per-URI ceilings.',
  '#  - Bot protection requires a paid provider integration; this generator',
  '#    declares the anti-bot block but does not configure a provider.',
  '#  - The ML model may block attacks not explicitly in our policy (its',
  '#    default web-attacks heuristics). Such blocks are open-appsec doing',
  '#    its own job, NOT Writ enforcement.',
  '',
].join('\n');

export const openappsecGenerator: OpenAppSecGenerator = {
  name: 'openappsec',
  targets: ['openappsec'],

  get lastWarnings(): readonly string[] {
    return openappsecLastWarnings;
  },

  generate(spec: SpecIR): ConfigArtifact[] {
    // Spec-hygiene: warn on url-typed params missing SSRF policy. Wave-11 W11-A.
    openappsecLastWarnings = collectSsrfPolicyWarnings(spec, 'openappsec').map((w) => w.message);

    const doc = buildDoc(spec);

    const yamlBody = yaml.dump(doc, {
      indent: 2,
      lineWidth: 120,
      noRefs: true,
      sortKeys: false,
    });

    const policyContent = `${HEADER}${yamlBody}`;

    // Wave-8: emit the OpenAPI schema fragment that the practice's
    // `openapi-schema-validation.files:` field references. Without this the
    // agent has nothing to validate request bodies against (the `configmap:`
    // / `files:` list was empty pre-wave-8).
    const fragment = buildOpenApiFragment(spec);
    const fragmentYaml = yaml.dump(fragment, {
      indent: 2,
      lineWidth: 120,
      noRefs: true,
      sortKeys: false,
    });
    const fragmentContent =
      '# Generated by Writ — DO NOT EDIT BY HAND.\n' +
      '# OpenAPI schema fragment for open-appsec schema validation.\n' +
      '# Referenced by practices[].openapi-schema-validation.files: in policy.yaml.\n' +
      '# Mount this file at the path declared there (default: /ext/appsec/openapi-schema.yaml).\n' +
      fragmentYaml;

    return [
      { path: 'openappsec/policy.yaml', content: policyContent, format: 'yaml' },
      { path: 'openappsec/openapi-schema.yaml', content: fragmentContent, format: 'yaml' },
    ];
  },

  capabilities(): CapabilityMatrix {
    // Honest matrix after wave-7 E2E validation against ghcr.io/openappsec/agent-unified.
    // See packages/cli/src/generators/openappsec/STATUS.md for the per-field rationale.
    return {
      fields: {
        // Wave-8: request schema is now enforced via the OpenAPI fragment
        // referenced by openapi-schema-validation.files:. The agent parses
        // the fragment and validates inbound bodies against the per-property
        // rules. Marked `partial` (not `full`) because (a) the ML model
        // needs baseline traffic to reach steady-state recall — under
        // prevent-learn with no learned state, it lets some malformed
        // payloads through and (b) per-property `mitigates:` hints are
        // Writ-internal and not consumed by the agent.
        'request.schema': 'partial',
        'request.contentType': 'partial',
        'request.maxBodySize': 'partial', // via web-attacks max-body-size-kb (practice-wide)
        'response.schema': 'unsupported',
        'response.contentType': 'unsupported',
        'response.stripUnknownFields': 'unsupported',
        rateLimit: 'partial', // per-URI only; identifier modes (user-id/api-key) collapse

        // Open-appsec is not an identity layer. These belong at an OIDC sidecar.
        'authentication.type': 'unsupported',
        'authentication.jwksUri': 'unsupported',
        'authentication.issuer': 'unsupported',
        'authentication.audience': 'unsupported',
        authorization: 'unsupported',

        // L7 inspection won't validate HMAC signatures.
        'request.signature': 'unsupported',

        // Anti-bot block emitted but provider integration is a paid SKU.
        botProtection: 'partial',

        cors: 'unsupported',
        ipPolicy: 'unsupported',
        mtls: 'unsupported',
        cacheable: 'unsupported',
        timeout: 'unsupported',
        deprecated: 'unsupported',
      },
    };
  },
};

export default openappsecGenerator;
